---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep
  labels:
    app: mysql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "employeedb"
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
---
kind: Service                             # Defines to create Service type Object
apiVersion: v1
metadata:
  name: mysql-okts-test
spec:
  ports:
    - port: 3306                         # Containers port exposed
      targetPort: 3306
  selector:
    app: mysql-app               # Apply this service to any pods which has the specific label
  type:  NodePort

