name: 'Deploy to minikube'

on: workflow_dispatch

jobs:
  deploy:
    name: Springapp Deploy
    runs-on: self-hosted
    steps:
    
    - name: Get Manifest File
      uses: actions/checkout@v2
      
  #  - name: Create Kubeconfig
  #    run: |
  #      echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
  #      cat ${HOME}/.kube/config
        
  #  - name: Use context
  #    run: kubectl config use-context octobay-api
        
        
    - name: Apply the manifest file
      run: sudo kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f mysql-pod.yml
    
