name: 'Deploy to minikube'

on: workflow_dispatch

jobs:
  deploy:
    name: Springapp Deploy
    runs-on: self-hosted
    steps:
    
    - name: Get Manifest File
      uses: actions/checkout@v2
      
    - name: Switch to root user
      run: |
        echo $PWD
        whoami 
        sudo -i
        whoami
        
        
  #  - name: Apply the manifest file
  #    run: kubectl apply -f .kube/manifest-test.yml
    
