name: 'Deploy to minikube'

on: workflow_dispatch

jobs:
  deploy:
    name: Springapp Deploy
    runs-on: self-hosted
    steps:
    
    - name: Get Manifest File
      uses: actions/checkout@v2
      
    - name: Create Kubeconfig
      run: |
        mkdir ${HOME}/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
        cat ${HOME}/.kube/config
        
    - name: Use context
      run: kubectl config use-context octobay-api
        
        
    - name: Apply the manifest file
      run: kubectl apply -f .kube/manifest-test.yml
    
